### ISSUE TITLE
 Class 'Psr\Log\NullLogger' not found

### ISSUE THREAD

**Issue by rconfig** [yuloh/expect#1]
get this when running cat example from the CLI

PHP Fatal error:  Uncaught Error: Class 'Psr\Log\NullLogger' not found in /var/www/html/expect/src/Expect.php:55
Stack trace:
#0 /var/www/html/expect/src/Expect.php(71): Yuloh\Expect\Expect->__construct('cat', NULL, NULL)
#1 /var/www/html/expect/test.php(6): Yuloh\Expect\Expect::spawn('cat')
#2 {main}
  thrown in /var/www/html/expect/src/Expect.php on line 55

latest psr/log installed

[root@localhost expect]# composer show -i | grep log
Do not run Composer as root/super user! See https://getcomposer.org/root for details
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
psr/log                           1.0.2  Common interface for logging libraries

**Comment by matt-allan** [comment]
Hi,

Sorry I didn't see this, my github feed is pretty noisy.

does your file `test.php` have `require __DIR__ . '/vendor/autoload.php'` at the top?  It sounds like an issue with your autoloader configuration but it's hard to say without more info.

**Comment by rconfig** [comment]
fixed it, thanks
